import type { Metadata } from "next";
import "./globals.css";
import BaseLayoutClient from "@/components/custom/BaseLayoutClient";
import {Toaster} from "sonner";
import {ResponsiveToaster} from "@/components/custom/ResponsiveToaster";

export const metadata: Metadata = {
  title: "ShelfSpace",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`antialiased`}>
                <BaseLayoutClient>{children}</BaseLayoutClient>
                <ResponsiveToaster />
            </body>
        </html>
    );
}
