import type { Metadata } from "next";
import "./globals.css";
import {BreadCrumb} from "@/components/custom/BreadCrumb";
import BaseLayoutClient from "@/components/custom/BaseLayoutClient";

export const metadata: Metadata = {
  title: "Digital Storage",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`antialiased`}>
                <BaseLayoutClient>{children}</BaseLayoutClient>
            </body>
        </html>
    );
}
